---
- name: "eos.backup: fetch network configuration"
  eos_config:
    backup: "true"
  register: r_eos_config

- name: "eos.backup: remove non configuration lines"
  changed_when: false
  lineinfile:
    path: "{{ r_eos_config.backup_path }}"
    regexp: "{{ item }}"
    state: "absent"
  loop:
    - '^\!.*'

- name: "eos.backup: save configuration to git_store"
  copy:
    src: "{{ r_eos_config.backup_path }}"
    dest: "{{ git_path }}/{{ inventory_hostname }}/config/running.cfg"
    force: "yes"
  notify: git_sync
